<a href="https://colab.research.google.com/github/kmin0528/wanted-pre-onboarding-challenge-data/blob/main/Numpy_Quiz_%EB%AC%B8%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# 필요한 라이브러리를 불러옵니다.
import numpy as np

### 1. 값이 10~49인 numpy array를 만드세요

In [19]:
z = np.array(list(i for i in range(10,50)))
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 2. z를 반전하세요.

In [42]:
z = np.array(list(reversed(z)))
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### 3. 반전시킨 z 매트릭스를 10 x 4 매트릭스로 바꾸세요.

In [61]:
arr = np.empty((0,4), int)

for i in range(0, len(z), 4):
  arr = np.append(arr, np.array([z[i:i+4]]), axis = 0)
z = arr
print(z)

[[49 48 47 46]
 [45 44 43 42]
 [41 40 39 38]
 [37 36 35 34]
 [33 32 31 30]
 [29 28 27 26]
 [25 24 23 22]
 [21 20 19 18]
 [17 16 15 14]
 [13 12 11 10]]


### 4. x에서 0이 아닌 요소의 색인을 찾아보세요.

In [63]:
li = [5,6,8,0,1,0,7]

print(li.index(0))

3


In [69]:
x = np.array([5,6,8,0,1,0,7])
nz_idx = np.where(x != 0)

print(nz_idx)

(array([0, 1, 2, 4, 6]),)


### nan 값 이해하기



In [70]:
print(np.nan == np.nan)
print(np.isnan(np.nan))

import math
print(0.3 == 3 * 0.1)
print(math.isclose(0.1 + 0.2, 0.3))

False
True
False
True


### 5. 12 x 12 매트릭스를 만들어 바둑판 패턴으로 0과 1을 채우세요

In [74]:
x = np.zeros((12, 12))
print(x, end='\n\n')
###############
# 슬라이싱을 사용하세요

x = np.ones((12,12))
###############
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 6. np.tile 을 이용해서 동일한 바둑판 배턴을 만들어보세요

In [79]:
x = np.tile(np.array([0,1]), (12,6))
print(x)

[[0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1]]


### 7. 1차원 배열이 x에서 값이 5~10인 요소를 0으로 바꾸세요

In [90]:
x = np.array([2,5,3,8,3,34,23,7,10])
print(x)
##################
# 필터링을 사용하세요.

#d = (x >= 5) & (x <= 10)

for i in range(len(x)):
  if x[i] >= 5 and x[i] <= 10:
    x[i] = 0

##################
print(x)

[ 2  5  3  8  3 34 23  7 10]
[ 2  0  3  0  3 34 23  0  0]


### 8. 0에서 100 사이의 값으로 크기가 10인 1차원 array를 만드세요

In [92]:
x = np.linspace(0,100,10)
print(x)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


### 9. np.allclose() 함수를 사용하여 2개의 array가 같은지를 확인해보세요

In [98]:
A = np.array([1e10,1e-8])
B = np.array([1.00001e10,1e-9])

equal = np.allclose(A, B)
print(equal)

True


### 10. 데카르트 좌표를 나타내는 랜덤 8 x 2 행렬을 고려하여 극좌표로 변환해보세요.

In [100]:
coord = np.random.random((10,2))
x, y = coord[:,0], coord[:,1]
r = np.sqrt(x**2+y**2)
theta = np.arctan2(y,x)
ploar_coord = np.concatenate([r[:,np.newaxis], theta[:,np.newaxis]],axis=1)
print(ploar_coord)

[[1.11062258 0.86854617]
 [0.58140847 1.44647532]
 [0.52538111 0.2256849 ]
 [1.30594061 0.82943085]
 [0.41325309 0.19584629]
 [0.915007   0.33788555]
 [0.99874406 1.09375409]
 [0.75265919 0.19020734]
 [1.20326654 0.8407049 ]
 [0.90823616 1.03967911]]
